typography_spectrum: 0.762082964880392
color:
  brandStrength: 0.379025106318295
  saturation: 0.7990343985147774
  brandColors:
    - '#004358'
    - '#1F8A70'
    - '#BEDB39'
    - '#FFE11A'
    - '#FD7400'
  lightness: 0.7558921920135617
  rhythmicContrast: 0.6555577975232154
layout_spectrum: 0.7741455396171659
author:
  name: Charles Baker
  email: charlesabaker2010@gmail.com
name: Good Soil Coffee
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
title: Good Soil Coffee
description: Taste matters.
