typography_spectrum: 0.5466618393547833
color:
  brandStrength: 0.379025106318295
  saturation: 0.7990343985147774
  brandColors:
    - '#004358'
    - '#1F8A70'
    - '#BEDB39'
    - '#FFE11A'
    - '#FD7400'
  lightness: 0.7558921920135617
  rhythmicContrast: 0.6555577975232154
layout_spectrum: 0.3297872
analytics:
  google: UA-81485606-1
author:
  name: Charles Baker
  email: charlesabaker2010@gmail.com
name: Good Soil Coffee
navigation:
  - name: Try some Coffee!
    id: e9fd1cb6-3559-4bfe-a643-b590a0668837
    type: content
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
title: Good Soil Coffee
description: Taste matters.
